export const WC2026_TEAMS = [
	{ name: 'Mexico', flag: 'MX', group: 'A' },
	{ name: 'Uruguay', flag: 'UY', group: 'A' },
	{ name: 'Poland', flag: 'PL', group: 'A' },
	{ name: 'South Africa', flag: 'ZA', group: 'A' },
	{ name: 'USA', flag: 'US', group: 'B' },
	{ name: 'Brazil', flag: 'BR', group: 'B' },
	{ name: 'Japan', flag: 'JP', group: 'B' },
	{ name: 'Tunisia', flag: 'TN', group: 'B' },
	{ name: 'Canada', flag: 'CA', group: 'C' },
	{ name: 'Germany', flag: 'DE', group: 'C' },
	{ name: 'Morocco', flag: 'MA', group: 'C' },
	{ name: 'Ecuador', flag: 'EC', group: 'C' },
	{ name: 'Argentina', flag: 'AR', group: 'D' },
	{ name: 'England', flag: 'GB', group: 'D' },
	{ name: 'Senegal', flag: 'SN', group: 'D' },
	{ name: 'Bolivia', flag: 'BO', group: 'D' },
	{ name: 'France', flag: 'FR', group: 'E' },
	{ name: 'Spain', flag: 'ES', group: 'E' },
	{ name: 'South Korea', flag: 'KR', group: 'E' },
	{ name: 'New Zealand', flag: 'NZ', group: 'E' },
	{ name: 'Portugal', flag: 'PT', group: 'F' },
	{ name: 'Colombia', flag: 'CO', group: 'F' },
	{ name: 'Ghana', flag: 'GH', group: 'F' },
	{ name: 'Qatar', flag: 'QA', group: 'F' },
	{ name: 'Netherlands', flag: 'NL', group: 'G' },
	{ name: 'Croatia', flag: 'HR', group: 'G' },
	{ name: 'Nigeria', flag: 'NG', group: 'G' },
	{ name: 'Chile', flag: 'CL', group: 'G' },
	{ name: 'Belgium', flag: 'BE', group: 'H' },
	{ name: 'Switzerland', flag: 'CH', group: 'H' },
	{ name: 'Egypt', flag: 'EG', group: 'H' },
	{ name: 'Panama', flag: 'PA', group: 'H' },
	{ name: 'Denmark', flag: 'DK', group: 'I' },
	{ name: 'Serbia', flag: 'RS', group: 'I' },
	{ name: 'Cameroon', flag: 'CM', group: 'I' },
	{ name: 'Costa Rica', flag: 'CR', group: 'I' },
	{ name: 'Austria', flag: 'AT', group: 'J' },
	{ name: 'Australia', flag: 'AU', group: 'J' },
	{ name: 'Ivory Coast', flag: 'CI', group: 'J' },
	{ name: 'Honduras', flag: 'HN', group: 'J' },
	{ name: 'Italy', flag: 'IT', group: 'K' },
	{ name: 'Saudi Arabia', flag: 'SA', group: 'K' },
	{ name: 'DR Congo', flag: 'CD', group: 'K' },
	{ name: 'Jamaica', flag: 'JM', group: 'K' },
	{ name: 'Turkey', flag: 'TR', group: 'L' },
	{ name: 'Paraguay', flag: 'PY', group: 'L' },
	{ name: 'Indonesia', flag: 'ID', group: 'L' },
	{ name: 'Iraq', flag: 'IQ', group: 'L' }
] as const;

export const STAGE_LABELS: Record<string, string> = {
	group: 'Phase de groupes',
	round_of_32: 'Huitièmes de finale',
	round_of_16: 'Seizièmes de finale',
	quarters: 'Quarts de finale',
	semis: 'Demi-finales',
	third: 'Match pour la 3ème place',
	final: 'Finale'
};

export const COUNTRIES = [
	'Algérie', 'Argentine', 'Australie', 'Autriche', 'Belgique', 'Bolivie', 'Brésil',
	'Cameroun', 'Canada', 'Chili', 'Colombie', 'Congo RD', 'Costa Rica', 'Côte d\'Ivoire',
	'Croatie', 'Danemark', 'Ecosse', 'Equateur', 'Espagne', 'Etats-Unis', 'France',
	'Ghana', 'Allemagne', 'Angleterre', 'Honduras', 'Hongrie', 'Indonésie', 'Irak',
	'Iran', 'Irlande', 'Italie', 'Jamaïque', 'Japon', 'Maroc', 'Mexique',
	'Nigéria', 'Nouvelle-Zélande', 'Pays-Bas', 'Panama', 'Paraguay', 'Pérou',
	'Pologne', 'Portugal', 'Qatar', 'Arabie Saoudite', 'Sénégal', 'Serbie',
	'Corée du Sud', 'Afrique du Sud', 'Suisse', 'Tunisie', 'Turquie', 'Uruguay', 'Autre'
].sort();
